spring:
  profiles:
    active: local # 기본적으로 local이 선택된다는 뜻
  mail:
    host: smtp.gmail.com
    port: 587
    username: jangka512@gmail.com
    password: pxwczegttsjnghbr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://127.0.0.1:3306/wikenDevelopment?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
  session:
    store-type: none
mybatis:
  type-aliases-package: com.jhs.wiken.vo
custom:
  siteName : 위켄
  siteMainUri: http://localhost:8077
  notifyEmailFrom: no-reply@no-reply.com
  logging:
    dir: log
    level: debug
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always
    include-binding-errors: always