spring:
  profiles: production
  servlet:
    multipart:
      location: /tmp
  datasource:
    username: sbsstLocal
    password: sbslocal123414
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/wikenProduction?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    timeout: 6000
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
custom:
  siteMainUri: https://wiken.io
  genFileDirPath: /opt/tomcat/latest/wiken.io-file
  logging:
    dir: /tmp/wiken-log
    level: info